package me.mystock.greendao;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import me.mystock.greendao.FavoriteList;
import me.mystock.greendao.StockUser;

import me.mystock.greendao.FavoriteListDao;
import me.mystock.greendao.StockUserDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig favoriteListDaoConfig;
    private final DaoConfig stockUserDaoConfig;

    private final FavoriteListDao favoriteListDao;
    private final StockUserDao stockUserDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        favoriteListDaoConfig = daoConfigMap.get(FavoriteListDao.class).clone();
        favoriteListDaoConfig.initIdentityScope(type);

        stockUserDaoConfig = daoConfigMap.get(StockUserDao.class).clone();
        stockUserDaoConfig.initIdentityScope(type);

        favoriteListDao = new FavoriteListDao(favoriteListDaoConfig, this);
        stockUserDao = new StockUserDao(stockUserDaoConfig, this);

        registerDao(FavoriteList.class, favoriteListDao);
        registerDao(StockUser.class, stockUserDao);
    }
    
    public void clear() {
        favoriteListDaoConfig.getIdentityScope().clear();
        stockUserDaoConfig.getIdentityScope().clear();
    }

    public FavoriteListDao getFavoriteListDao() {
        return favoriteListDao;
    }

    public StockUserDao getStockUserDao() {
        return stockUserDao;
    }

}
