package me.mystock.greendao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table t_FavoriteList.
 */
public class FavoriteList {

    private Long id;
    /** Not-null value. */
    private String stockName;
    private String stockId;

    public FavoriteList() {
    }

    public FavoriteList(Long id) {
        this.id = id;
    }

    public FavoriteList(Long id, String stockName, String stockId) {
        this.id = id;
        this.stockName = stockName;
        this.stockId = stockId;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    /** Not-null value. */
    public String getStockName() {
        return stockName;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setStockName(String stockName) {
        this.stockName = stockName;
    }

    public String getStockId() {
        return stockId;
    }

    public void setStockId(String stockId) {
        this.stockId = stockId;
    }

}
